environment:
  node_version: "6"
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

skip_commits:
  message: /\[ci skip\]/

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - ps: Install-Product node $env:node_version
  - yarn install
  - echo %PATH%
  - java -version
  - mvnw.cmd --version

test_script:
  - mvnw.cmd package -Pprod

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
