version: '2'
services:
    jhgrad-app:
        image: jhgrad
        external_links:
            - jhgrad-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jhgrad
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhgrad-postgresql:
        extends:
            file: postgresql.yml
            service: jhgrad-postgresql
